/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ct_consulta_ajax;
import model.evolution_chain;
import model.evolution_chain_chain_evolves_to;
import model.evolution_chain_chain_evolves_to_evolves_to;

/**
 *
 * @author yair
 */
public class jd_cadena_evolucion extends javax.swing.JDialog {

    /**
     * Creates new form jd_cadena_evolucion
     */
    //private ct_consulta_ajax ct = new ct_consulta_ajax();
    private ct_consulta_ajax ct = new ct_consulta_ajax();

    public jd_cadena_evolucion(java.awt.Frame parent, boolean modal, String url) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.CargarImagenes(url);
    }

    public void CargarImagenes(String url) {
        evolution_chain evolutionchain = ct.evolution_chain(url);
        evolution_chain_chain_evolves_to[] getevolution_detail = evolutionchain.getChain().getEvolves_to();

        evolution_chain_chain_evolves_to[] probando = evolutionchain.getChain().getEvolves_to();
        evolution_chain_chain_evolves_to_evolves_to[] prueba2 = probando[0].getEvolves_to();
        System.out.println(prueba2.length > 0 );
        if (prueba2.length > 0) {
            String[] primerurl = prueba2[0].getSpecies().getUrl().split("/");
            ct.set_image_pokemon(jLabel_fase1, primerurl[6]);
            jLabel_title_fase1.setText(prueba2[0].getSpecies().getName());

        }
        if (getevolution_detail.length > 0) {
            String[] segundourl = getevolution_detail[0].getSpecies().getUrl().split("/");
            ct.set_image_pokemon(jLabel_fase2, segundourl[6]);
            jLabel_title_fase2.setText(getevolution_detail[0].getSpecies().getName());
        }
        if (evolutionchain.getChain() != null) {
            String[] tercerUrl = evolutionchain.getChain().getSpecies().getUrl().split("/");
            ct.set_image_pokemon(jLabel_fase3, tercerUrl[6]);
            jLabel_title_fase3.setText(evolutionchain.getChain().getSpecies().getName());
        }
        /*  System.out.println(primerurl[6]);
        System.out.println(segundourl[6]);
        System.out.println(tercerUrl[6]);*/

 /*  System.out.println(prueba2[0].getSpecies().getUrl());
        System.out.println(getevolution_detail[0].getSpecies().getUrl());
        System.out.println(evolutionchain.getChain().getSpecies().getUrl());*/
        //  System.out.println(prueba2[0].getSpecies().getUrl(). substring(prueba2[0].getSpecies().getUrl().lastIndexOf("/"), prueba2[0].getSpecies().getUrl().length()-1));
        //  System.out.println(getevolution_detail[0].getSpecies().getUrl());
        //    System.out.println(evolutionchain.getChain().getSpecies().getUrl());

        /*  ct.set_image_pokemon(jLabel_fase1, primerurl[6]);
        ct.set_image_pokemon(jLabel_fase2, segundourl[6]);
        ct.set_image_pokemon(jLabel_fase3, tercerUrl[6]);*/

 /*  jLabel_title_fase1.setText(prueba2[0].getSpecies().getName());
        jLabel_title_fase2.setText(getevolution_detail[0].getSpecies().getName());
        jLabel_title_fase3.setText(evolutionchain.getChain().getSpecies().getName());*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_fase3 = new javax.swing.JLabel();
        jLabel_fase1 = new javax.swing.JLabel();
        jLabel_fase2 = new javax.swing.JLabel();
        jLabel_title_fase2 = new javax.swing.JLabel();
        jLabel_title_fase3 = new javax.swing.JLabel();
        jLabel_title_fase1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_fase3.setText(".....");

        jLabel_fase1.setText("...");

        jLabel_fase2.setText("....");

        jLabel_title_fase2.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        jLabel_title_fase2.setText("...");

        jLabel_title_fase3.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        jLabel_title_fase3.setText("jLabel1");

        jLabel_title_fase1.setFont(new java.awt.Font("DialogInput", 0, 36)); // NOI18N
        jLabel_title_fase1.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel_title_fase1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_title_fase2)
                .addGap(223, 223, 223))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_fase1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jLabel_fase2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel_fase3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(519, 519, 519)
                        .addComponent(jLabel_title_fase3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_title_fase2)
                    .addComponent(jLabel_title_fase1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fase2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fase1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_title_fase3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_fase3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jd_cadena_evolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jd_cadena_evolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jd_cadena_evolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jd_cadena_evolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jd_cadena_evolucion dialog = new jd_cadena_evolucion(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_fase1;
    private javax.swing.JLabel jLabel_fase2;
    private javax.swing.JLabel jLabel_fase3;
    private javax.swing.JLabel jLabel_title_fase1;
    private javax.swing.JLabel jLabel_title_fase2;
    private javax.swing.JLabel jLabel_title_fase3;
    // End of variables declaration//GEN-END:variables
}
